### ISSUE TITLE
可以有支持 source map ？

### ISSUE THREAD

**Issue by JoeBBChen** [lizhiyao/sentry-miniapp#12]
如题。

**Comment by lizhiyao** [comment]
考虑过 source map 的支持，不过目前小程序的 source map 只能登录官方管理后台后下载，对于自动化/工程化去支持 source map 带来了一定的挑战。

你目前有什么思路吗？ @JoeBBChen

**Comment by NullYing** [comment]
小程序开发者工具会生成source map,在macos上提取过,但是没有成功载入到sentry

**Comment by lizhiyao** [comment]
Duplicate of #20
