### ISSUE TITLE
使用 onUnhandledRejection 捕获 Promise 异常

### ISSUE THREAD

**Issue by Amorites** [lizhiyao/sentry-miniapp#16]
https://developers.weixin.qq.com/miniprogram/dev/api/base/app/app-event/wx.onUnhandledRejection.html

微信小程序基础库2.10已经正式支持了`onUnhandledRejection`，我看这部分代码现在注释掉了，应该可以弄回来了

**Comment by lizhiyao** [comment]
官方文档中提到「安卓平台暂时不会派发该事件」且对基础版本库要求为「2.10.0」，感觉这个功能是一件重要但是不紧急的事情。

**Comment by lizhiyao** [comment]
已实现 @Amorites 

欢迎试用
