### ISSUE TITLE
支持第三方小程序框架吗, 比如 Taro ?

### ISSUE THREAD

**Issue by dpyzo0o** [lizhiyao/sentry-miniapp#17]
RT

**Comment by lizhiyao** [comment]
理论上是支持的，因为 Taro 等第三方框架最终的编译目标是各个平台的「官方原生」的小程序。

具体实践上，我还没有尝试过。你可以试一下然后在这个 issue 下给个准确答案。 @dpyzo0o    

晚点我找个时间也可以试一下。

**Comment by dpyzo0o** [comment]
试了一下, 可以正常使用

**Comment by dpyzo0o** [comment]
BTW, 群二维码好像失效了, 能再发一个不

**Comment by lizhiyao** [comment]
> BTW, 群二维码好像失效了, 能再发一个不

已更新 @dpyzo0o
