### ISSUE TITLE
Promise 中异常没有上报

### ISSUE THREAD

**Issue by melunar** [lizhiyao/sentry-miniapp#19]
参考了demo，promise上报没有看到效果，现象好像是：promise上报跟普通错误同时发生，promise上报就失效了，代码如下
`
  onShow() {  

    console.log(this.data[Math.random() * 100000]) // 可以上报  
    new Promise((resovle, reject) => {  
      console.log(this.Promise[Math.random()])()  
      resovle()  
    })  
    .then((res) => {  
      console.log(res)  
    }, (err) => {  
      // console.error(err)  
      Sentry.captureException(err)  //  无法上报  
    })  
  }  
`

**Comment by lizhiyao** [comment]
`console.log(this.data[Math.random() * 100000]) `  代码执行时已经报错了，其后的 js 代码还会执行吗？ @melunar
