### ISSUE TITLE
modification of global variable "Function.prototype.toString" is not allowed when using plugins at app.json

### ISSUE THREAD

**Issue by hu-zhi-hang** [lizhiyao/sentry-miniapp#21]
@sentry/core 中的 FunctionToString 类里面的代码执行了 `Function.prototype.toString = function(this: WrappedFunction, ...args: any[]): string` 导致小程序报错，不知道这个有没办法解决呢
![image](https://user-images.githubusercontent.com/8455958/78866778-9c939700-7a72-11ea-8a3e-606e6e3eb212.png)

**Comment by lizhiyao** [comment]
你是如何确定小程序的报错是由于 @sentry/core 中的 FunctionToString 类给 Function.prototype.toString 赋值导致的呢？

希望提供下更详细的排查信息。

**Comment by lizhiyao** [comment]
看上去是微信插件机制的限制。

https://developers.weixin.qq.com/community/develop/doc/000ea418f4cc1066ca77439a357800

**Comment by lizhiyao** [comment]
https://developers.weixin.qq.com/community/develop/doc/000a6257f88838dee3288f66451000?highLine=%2520not%2520allowed%2520when%2520using%2520plugins%2520at%2520app.json

![image](https://user-images.githubusercontent.com/8143023/79410443-019b3f80-7fd3-11ea-91fe-854b196f3372.png)

**Comment by lizhiyao** [comment]
你可以使用更高的基础库试试。 @hu-zhi-hang

**Comment by atzcl** [comment]
小程序直播插件会冻结全局对象，只能选择去掉 sentry 对 `Function.prototype.toString` 的重写了 😂
