### ISSUE TITLE
原生微信小程序，上报成功了，但是sentry后台没有错误日志，知道什么原因吗

### ISSUE THREAD

**Issue by xingkai17** [lizhiyao/sentry-miniapp#24]
![image](https://user-images.githubusercontent.com/7419238/81470242-53269b00-921c-11ea-8e6b-dd5d238b74c0.png)
有上报记录，但是后台没有记录

**Comment by Sandy-Ding-Airwallex** [comment]
是不是没有开启`增强编译`?

**Comment by xingkai17** [comment]
嗯，但是我关了也不行，并且把es6转es5也关了，也不行，还是一样可以上报错误，但是后台没记录

**Comment by Sandy-Ding-Airwallex** [comment]
不是要打开吗? 关了也不行是什么意思.  我本来也是你这样, 开了就好了

**Comment by xingkai17** [comment]
也是一样的效果。

**Comment by lizhiyao** [comment]
@xingkai17 你遇到的这个问题解决了吗？

**Comment by lizhiyao** [comment]
暂时无法复现问题，先将 issue 关闭
