### ISSUE TITLE
错误信息只上传了一半

### ISSUE THREAD

**Issue by imyellow** [lizhiyao/sentry-miniapp#26]
一开始在 sentry 看到错误信息，怎么都看不全，还以为是 sentry 隐藏了，调试接口发现上报就少了。

![QQ20200612-150959](https://user-images.githubusercontent.com/3270774/84475314-e856fc80-acbe-11ea-8476-557756fae74c.png)

在小程序开发工具内调试发现传到服务器的 message 只有前面一部分，后面被`...`替代了

<img width="660" alt="QQ20200612-151409@2x" src="https://user-images.githubusercontent.com/3270774/84475579-63b8ae00-acbf-11ea-8165-0da1b5cc03c6.png">

![image](https://user-images.githubusercontent.com/3270774/84475925-f0fc0280-acbf-11ea-9ca0-e26b1f2b8d75.png)

是在所有页面的 Error 回调里写的，这样写应该是正确的吧
![image](https://user-images.githubusercontent.com/3270774/84476257-72539500-acc0-11ea-8965-967801b805ce.png)

**Comment by lizhiyao** [comment]
反馈已收到，我会尽快修复

**Comment by lizhiyao** [comment]
V0.9.5 已经修复 @imyellow
