### ISSUE TITLE
基于mpvue的微信小程序可以支持吗？另外交流群二维码失效了，可以更新下吗？

### ISSUE THREAD

**Issue by Roat** [lizhiyao/sentry-miniapp#3]

**Comment by Roat** [comment]
基于mpvue的微信小程序可以支持吗？另外交流群二维码失效了，可以更新下吗？或者有没有其他的加群方式

**Comment by lizhiyao** [comment]
> 基于mpvue的微信小程序可以支持吗？另外交流群二维码失效了，可以更新下吗？或者有没有其他的加群方式

1. 微信交流群二维码已更新
2. 理论上 sentry-miniapp 是支持使用 mpvue 开发的小程序的，因为 mpvue 最终会把源码编译为符合微信小程序官方形式的代码。只需要安装、引用并初始化 sentry-miniapp 即可。

按照 [mpvue 官方文档 - 如何捕获 app 的 onError](http://mpvue.com/qa.html)的说法，在 app 的根组件上添加名为 onError 的回调函数中，也可以使用 sentry-miniapp 主动进行异常上报。

我在项目中增加了一个 demo：`examples/weapp-mpvue` 。 发现在 `examples/weapp-mpvue/src/App.vue` 增加了 `onLaunch` 、`onError` 函数，但是发现没有被调用；不过在项目中使用 `Sentry.captureException(); ` 是可以成功上报的。
 
成功上报的请求：
![image](https://user-images.githubusercontent.com/8143023/63920314-20b08580-ca73-11e9-9d94-b67b984dbee9.png)

Sentry 后台：
![image](https://user-images.githubusercontent.com/8143023/63921096-c0bade80-ca74-11e9-805d-951e5345dfcd.png)

**Comment by lizhiyao** [comment]
http://mpvue.com/mpvue/

![image](https://user-images.githubusercontent.com/8143023/79595247-1382fc80-8111-11ea-8bf1-9013b858c237.png)
