### ISSUE TITLE
sentry-miniapp 是否依赖sentry固定某个版本？

### ISSUE THREAD

**Issue by niceboybao** [lizhiyao/sentry-miniapp#31]
- sentry-miniapp 是否依赖sentry固定某个版本？

**Comment by lizhiyao** [comment]
在 sentry-miniapp 的代码实现上，是依赖了确定版本的 sentry-javascript 底层代码包的 https://github.com/lizhiyao/sentry-miniapp/blob/master/package.json：

![image](https://user-images.githubusercontent.com/8143023/89285741-834ad200-d683-11ea-8af2-379de47cc2e2.png)

会不定期对底层依赖的包进行升级

**Comment by lizhiyao** [comment]
不确定上述回答是否解决了你的困惑（PS. 我没有很理解你说的「sentry固定某个版本」指的是什么）。
