### ISSUE TITLE
小程序项目升 Taro 3.0 是编译中提示报错

### ISSUE THREAD

**Issue by HeiLiu** [lizhiyao/sentry-miniapp#35]
UnhandledPromiseRejectionWarning: Error: sentry-miniapp 暂不支持此平台

**Comment by lizhiyao** [comment]
原本在 Taro 3.0 之前的项目中使用时正常的，对吗？

可以提供一个 demo 或者其他相关信息吗？ @HeiLiu

**Comment by HeiLiu** [comment]
对 原来在项目 Taro 2.2.13 中是能够正常使用的、这两天给项目依赖升上 Taro 3.0 编译的时候发现有这个 error、公司的项目有点不好 demo

**Comment by lizhiyao** [comment]
1. 是微信小程序还是其他平台的小程序？
2. Taro 3.0 编译的时候，你这边的设置的编译目标平台有哪些呢？

https://github.com/lizhiyao/sentry-miniapp/blob/5fae3ae1040f7c39840909dde41d2e1d979a79a7/src/crossPlatform.ts#L61  根据源码，初步猜测是 Taro 3.0 编译时，在全局找不到 `wx`、`my`、`tt`、`dd`、`qq` 这些变量中的任何一个，就 throw 了 error

**Comment by HeiLiu** [comment]
我们目前就是编译微信小程序

**Comment by lizhiyao** [comment]
编译命令使用的是 `yarn build:weapp` 对吗？

https://nervjs.github.io/taro/docs/GETTING-STARTED#%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F
