### ISSUE TITLE
@sentry/utils v5.7.1版本移除了keysToEventMessage方法导致异常的问题

### ISSUE THREAD

**Issue by YuJinLei** [lizhiyao/sentry-miniapp#5]
**异常图片**

![image](https://user-images.githubusercontent.com/18626859/69631951-6cca9080-1089-11ea-87a7-9aafab1aeee8.png)

**异常描述**
sentry-miniapp中使用了 @sentry/utils v5.6.1的版本并且使用了自动更新，现在@sentry/utils已经更新至v5.7.1版本，并且移除了keysToEventMessage

![image](https://user-images.githubusercontent.com/18626859/69632115-9c799880-1089-11ea-9e51-a61404f40812.png)

**Comment by lizhiyao** [comment]
我把 sentry-miniapp 的核心依赖升级到了最新版本，并且指定了固定的依赖版本。

目前我在开发机上测试 sentry-miniapp 可以正常使用了，麻烦你再试试。 @YuJinLei 

同时也更新了交流群二维码，欢迎入群交流。

**Comment by YuJinLei** [comment]
> 我把 sentry-miniapp 的核心依赖升级到了最新版本，并且指定了固定的依赖版本。
> 
> 目前我在开发机上测试 sentry-miniapp 可以正常使用了，麻烦你再试试。 @YuJinLei
> 
> 同时也更新了交流群二维码，欢迎入群交流。
ok👌了
